[FIX] Allow no coordinates in a dataset
neurostuff/NiMARE pull request #407
Opened 2020-11-25 01:54 UTC by jdkent

Closes #405

Changes proposed in this pull request:

- return empty dataframe for coordinates to pass data validation during dataset creation.
- add test for empty dataset

I'm not sure if we want to allow an empty dataset object or explicitly test that at least one of either coordinates or images be set for this to be a valid "dataset" object.

2020-11-25 15:29 UTC, tsalo requested changes
Minor request. Other than that these changes make sense. Thanks!

2020-11-25 15:29 UTC, tsalo commented on nimare/utils.py
> +        return pd.DataFrame({"id": []})
Could you include these columns as well: "study_id", "contrast_id", "x", "y", "z", and "space".

2020-11-30 19:31 UTC, tsalo approved these changes
The changes look good to me! I think we could expand the testing at some point, but I'm fine with a smoke test for now.

2020-12-02 03:07 UTC, jdkent commented
merging to allow my continuing work on ibma generation

2020-12-02 03:08 UTC, merged