[REF] Write temporary files to the NiMARE data directory
neurostuff/NiMARE pull request #460
Opened 2021-03-12 16:12 UTC by tsalo

Closes None. In working on the NiMARE paper, I've had trouble with memory issues. At minimum, writing temporary files (created when the `low_memory` option is used) to the NiMARE data directory will make it easier for users to track the files and remove them as necessary.

Changes proposed in this pull request:

- Write temporary files created in `ALEKernel`, `MKDAKernel`, `KDAKernel`, and `ALESubtraction` to the NiMARE data directory instead of temporary directories.
- Log the temporary filenames. I'd love to log their sizes as well, but I'm not sure how to estimate the file size before it's created. It should just be a matter of the data type and the size though...

2021-03-12 16:57 UTC, tsalo commented
@tyarkoni @jdkent do you have any idea what could cause a bus error based on the proposed changes?

2021-03-12 18:13 UTC, jdkent commented
Don't totally understand the bus error, but `mkdtemp` must be doing some important stuff behind the scenes.
You can still use `mkdtemp` and specify where the temporary directory should be created (e.g., `mkdtemp(dir='/my/special/directory')`). If you want to ensure no file collisions, you can look into [mkstemp](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) instead, and those files can go into the nimare dataset directory.

Going back to the overarching problem, do you want to keep track of these files? or do you just want them to be deleted/cleaned up in a more timely manner?

I guess I don't know how useful those files are for debugging.

2021-03-12 18:21 UTC, tsalo commented
>You can still use mkdtemp and specify where the temporary directory should be created (e.g., mkdtemp(dir='/my/special/directory')).

I didn't know that! I'll try using tempfile again.

>Going back to the overarching problem, do you want to keep track of these files? or do you just want them to be deleted/cleaned up in a more timely manner?

I don't want to keep them around long-term, but I do want to have them someplace accessible in cases where the script may crash or otherwise fail to delete them.

2021-03-12 18:22 UTC, tsalo commented
>You can still use mkdtemp and specify where the temporary directory should be created (e.g., mkdtemp(dir='/my/special/directory')).

I didn't know that! I'll try using tempfile again.

>Going back to the overarching problem, do you want to keep track of these files? or do you just want them to be deleted/cleaned up in a more timely manner?

I don't want to keep them around long-term, but I do want to have them someplace accessible in cases where the script may crash or otherwise fail to delete them.

2021-03-12 18:22 UTC, tsalo commented
>You can still use mkdtemp and specify where the temporary directory should be created (e.g., mkdtemp(dir='/my/special/directory')).

I didn't know that! I'll try using tempfile again.

>Going back to the overarching problem, do you want to keep track of these files? or do you just want them to be deleted/cleaned up in a more timely manner?

I don't want to keep them around long-term, but I do want to have them someplace accessible in cases where the script may crash or otherwise fail to delete them.

2021-03-12 18:23 UTC, tsalo commented
>You can still use mkdtemp and specify where the temporary directory should be created (e.g., mkdtemp(dir='/my/special/directory')).

I didn't know that! I'll try using tempfile again.

>Going back to the overarching problem, do you want to keep track of these files? or do you just want them to be deleted/cleaned up in a more timely manner?

I don't want to keep them around long-term, but I do want to have them someplace accessible in cases where the script may crash or otherwise fail to delete them.

2021-03-12 19:16 UTC, tsalo commented
One thing that's really weird is that I get bus errors from this step on my HPC using the old code, but not using the new code. Hopefully solving the problem for the CI won't break things for the actual analyses I'm running.

2021-03-12 19:41 UTC, tsalo commented on nimare/meta/cbma/base.py
> +            os.remove(ma_values.filename)
@jdkent WDYT of this for cleanup?

2021-03-12 21:02 UTC, tsalo commented on nimare/meta/cbma/base.py
> +            os.remove(ma_values.filename)
It turns out that was a bad idea, and the kernel transformers can handle the memmap deletion internally.

2021-03-12 21:31 UTC, tsalo commented
Everything seems to be working (🤞), but the current cleanup removes the mem-mapped files, but leaves the empty temporary directories.

2021-03-13 01:19 UTC, jdkent requested changes
It looks like the code additions could fit nicely into two functions: `_create_memmap` and `_delete_memmap`

```
def _create_memmap(prefix, dtype, shape, logger, dirname="temporary_files"):
        start_time = datetime.datetime.now().strftime("%Y%m%dT%H%M%S")
        dataset_dir = _get_dataset_dir("temporary_files", data_dir=None)
        temp_dir = mkdtemp(prefix=prefix, dir=dataset_dir)
        filename = os.path.join(temp_dir, f"{prefix}_{start_time}.dat")
        logger.info(f"Temporary file written to {filename}")

        # Use a memmapped array
        return np.memmap(
            filename, dtype=dtype, mode="w+", shape=shape
        )
```

```
def _delete_memmap(arr, logger):
        logger.info(f"Removing {arr.filename}")
            os.remove(arr.filename)
            temp_dir = os.path.dirname(arr.filename)
            if len(os.listdir(temp_dir)) == 0:
                logger.info(f"Removing empty directory {temp_dir}")
                os.rmdir(temp_dir)
      return arr.filename # don't know if this should return anything...
```

This should help with readability and maintainability. (these functions will probably go in utils? (that's a cop-out)

2021-03-13 05:15 UTC, jdkent commented
methods where memmap is being used:

- ALESubtraction
  - created: _fit
  - deleted: _fit
- SCALE
  - created: _fit
  - deleted: _fit
- KernelTransformer
  - created: _transform
  - deleted: transform
- meta.utils
  -  created: compute_kda_ma (called in KDAKernel._transform)

I think I write a decorator for this, I'll open a pull request to your branch.
A decorator will help with being DRY (Don't Repeat Yourself), but it will look a little weird/black magicy.

2021-03-13 23:51 UTC, jdkent reviewed
Just a minor change and perhaps a unit test for `use_memmap`, but I can take on in another pull request, otherwise, LGTM!

2021-03-13 23:51 UTC, jdkent commented on nimare/meta/kernel.py
> +                return masked_ma_arr
```suggestion
                return transformed_maps[0][:, mask_data]
```

This looks like it can be reverted to what it was before

2021-03-13 23:51 UTC, jdkent commented on nimare/utils.py
> +def use_memmap(logger):
Might want a unit test for `use_memmap`, but I can do that in a separate pull request if you do not want to that here.

2021-03-14 15:11 UTC, jdkent approved these changes

2021-03-14 15:30 UTC, tsalo commented
@jdkent Thanks for all your help with this!

2021-03-14 15:30 UTC, merged