[WIP,DOC] Improve documentation of decoders
neurostuff/NiMARE pull request #506
Opened 2021-05-06 19:44 UTC by JulioAPeraza

Closes #436.

Changes proposed in this pull request:

- Improve the discrete decoders section (`methods/decoding.rst`).
- Add the continuous decoders section. Add a non-running example.

Open questions:

- Do we also want to add the encoders section as part of this pull request?

2021-09-23 16:19 UTC, tsalo commented
@JulioAPeraza Is this ready for review?

2021-09-23 20:47 UTC, JulioAPeraza commented
Yes, it is ready. Thanks!
In addition to the text and formulae from your NiMARE manuscript, I also incorporated text and a non-running example of the `CorrelationDecoder` with the `feature_group` argument, so the wording there may be a little confusing.

2021-09-24 23:44 UTC, tsalo commented
The math doesn't seem to be rendering properly. Are we missing the necessary plugin or is it maybe formatted for a different language (e.g., markdown)?

![image](https://user-images.githubusercontent.com/8228902/134749819-ea50f036-ee82-4304-bb7c-c83ec2f471b3.png)

2021-09-25 14:47 UTC, JulioAPeraza commented
I don't know what is causing this. I built the documentation locally with the same version (`v4.2.0`) of Sphinx that CircleCI used, and the math looked fine.
To generate the latex images, I used the extension `"sphinx.ext.imgmath"`, which is already in the `conf.py` file.

2021-09-25 14:54 UTC, tsalo commented
Hm, okay. It could be that the CI build job is just not configured correctly. This is one good reason for us to switch to using the RTD CI tool instead of CircleCI for the docs build, though I had trouble setting it up the last time I tried.

Anyway, I'm leaning toward merging and then fixing if there are problems.

2021-09-25 14:58 UTC, tsalo requested changes
I think these extra backticks might be part of the problem. The other thing is that I'm a little worried about the hardcoded examples becoming out-of-date as NiMARE is updated, since the API is still not all that stable, but I'm happy to merge with them included and re-evaluate if it becomes a problem.

Anyway, if you fix those extra backticks, then I'll approve. Everything else looks good to me.

2021-09-25 14:58 UTC, tsalo commented on docs/methods/decoding.rst
> +two probability distributions from LDA (:math:`P(word|topic)`` and :math:`P(topic|article)``),
```suggestion
two probability distributions from LDA (:math:`P(word|topic)` and :math:`P(topic|article)`), 
```

2021-09-25 20:50 UTC, JulioAPeraza commented
Do we need to install `latex` in the Docker image?

2021-09-27 20:46 UTC, tsalo commented
I'm thinking we should just merge and see how it goes. If there's a problem then we can fix later. Any concerns with me merging as-is?

2021-09-28 13:30 UTC, JulioAPeraza commented
Please, feel free to merge it. Thanks!

2021-09-28 14:12 UTC, merged