Do not zero out one-tailed z-statistics for p-values > 0.5
neurostuff/NiMARE pull request #693
Opened 2022-06-01 21:39 UTC by JulioAPeraza

Closes #511.

Changes proposed in this pull request:

- Do not zero out one-tailed z-statistics for p-values > 0.5. **Note:** p-value = 0.5 will still be set to 0, so logp and z-statistic maps will not completely match in that case.

2022-06-02 13:58 UTC, tsalo requested changes
The changes make sense to me. Can you add a new test that covers this case though (or expand an existing one)?

2022-06-07 19:21 UTC, JulioAPeraza commented
@tsalo if we don't zero out one-tailed z-statistics for p-values > 0.5, should we: (1) leave the negative value, (2) apply the abs() function since the values returned by this function should be unsigned z-statistics, or (3) replace the negative values with a small number `1.0e-300`?

2022-06-11 14:34 UTC, tsalo commented
I'm not sure... maybe someone else who has a better handle on stats can answer that?

2023-01-27 16:41 UTC, tsalo commented
@yifan0330 seemed to have a good handle on z-to-p conversion (and probably p-to-z conversion), given #748 and #749. @yifan0330 would you be willing to take a look at this?

2023-01-31 22:50 UTC, yifan0330 commented on nimare/tests/test_transforms.py
> +        (-1.959963, "one", 0.025),
I think it should be (-1.959963, "one", 0.975). I've corrected it in issue #748

2023-01-31 22:57 UTC, yifan0330 commented on nimare/tests/test_transforms.py
> +        (-1.959963, "one", 0.025),
This test case should be (-1.959964, "one", 0.0975). I think I've corrected in issue #748

2023-01-31 22:59 UTC, yifan0330 commented on nimare/tests/test_transforms.py
> +        ([0.0, 1.959963, -1.959963], "one", [0.5, 0.025, 0.025]),
([0.0, 1.959963, -1.959963], "one", [0, 0.025, 0.975])

2023-01-31 23:07 UTC, yifan0330 commented
> @yifan0330 seemed to have a good handle on z-to-p conversion (and probably p-to-z conversion), given #748 and #749. @yifan0330 would you be willing to take a look at this?

@JulioAPeraza @tsalo I saw you replace negative z value with values estimated by cdf, I am wondering if it's the same as taking absolute value of z (since `z` and `zval_cdf` have same value but opposite sign)? Also, I left two comments on testing case (I think z=-1.959964 corresponds to p=0.975 in one tail test).

2023-02-01 18:06 UTC, JulioAPeraza commented
Thanks so much, @yifan0330! I've incorporated your suggestions.
@tsalo Do you think this is ready to merge?

2023-02-01 18:08 UTC, tsalo approved these changes
@JulioAPeraza if @yifan0330 is happy with the changes then absolutely, I think it's good to merge.

2023-02-01 21:10 UTC, yifan0330 commented
> @JulioAPeraza if @yifan0330 is happy with the changes then absolutely, I think it's good to merge.

Yeah I am happy with Julio's changes :)

2023-02-01 21:15 UTC, JulioAPeraza commented
Thanks! Merging now.

2023-02-01 21:15 UTC, merged