Remove "dataset" `return_type` option from kernel transformers
neurostuff/NiMARE pull request #752
Opened 2022-11-11 21:14 UTC by JulioAPeraza

Closes #630.

Changes proposed in this pull request:

- Remove "dataset" `return_type` option from kernel transformers.
- I'm keeping `KernelTransformer._infer_names()`, just in case someone wants to generate image names and saves them in the `Dataset.images` dataframe for `CorrelationDistributionDecoder`, as shown in the test `test_CorrelationDistributionDecoder_smoke()`.

2022-12-07 16:34 UTC, tsalo requested changes
This definitely simplifies the code. Thanks! I've only requested a few minor changes.

2022-12-07 16:34 UTC, tsalo commented on nimare/meta/cbma/base.py
> +        # if maps_key in self.inputs_.keys():
Can you remove this commented-out code or, if it's meant as a comment and not commented-out code, convert it to a comment?

2022-12-07 16:34 UTC, tsalo commented on nimare/meta/kernel.py
> +            - Remove "dataset" `return_type` option.
Can you add this to the child classes' docstrings as well?

2022-12-07 16:34 UTC, tsalo commented on nimare/meta/kernel.py
>          return_type : {'sparse', 'array', 'image', 'dataset'}, optional
```suggestion
        return_type : {'sparse', 'array', 'image'}, optional
```

2022-12-20 17:26 UTC, JulioAPeraza commented
It looks like python 3.6 is no longer available in ubuntu-latest. 
@tsalo, @adelavega, @jdkent. Should we maintain supporting python 3.6?

2022-12-20 17:29 UTC, tsalo commented
I would have preferred to have a sunsetting timeline in place ahead of time, with deprecation warnings to users and the like for a few releases, but if we can't test on 3.6 then I think we should drop it. Probably worth jumping to 0.1.0 in that case though.

2022-12-20 17:31 UTC, JulioAPeraza commented
I think we can test 3.6 with ubuntu-20.04. What about adding the deprecation warnings for 0.0.13, and then dropping 3.6 for 0.1.0

2022-12-20 17:38 UTC, tsalo commented
That would be nice.

2022-12-20 18:22 UTC, adelavega commented
Python 3.6 is end-of-life already and 3.7 will be very soon (so I would add that to the deprecation cycle). 

This is true for many tools also, so I think users on 3.6 will have to upgrade to get the latest versions of most of the related scientific software regardless. 

But I'm not opposed to your plan if you want to go ahead with it!

2023-01-12 22:58 UTC, jdkent approved these changes
LGTM!

2023-01-13 14:53 UTC, merged